apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-portfolio-dev
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cloudflared.yaml
images:
  - name: ghcr.io/joex422/web-portfolio
    newTag: dev-794e2ad5c3fc57da2c266a1507ea9b28358815f3
