apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-portfolio-dev
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cloudflared.yaml
images:
  - name: ghcr.io/joex422/web-portfolio
    newTag: dev-43015b5fbfba1813ee26e94193ac0c9e9b9046dd
