apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-portfolio-dev
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cloudflared.yaml
images:
  - name: ghcr.io/joex422/web-portfolio
    newTag: dev-80028649009755485e00d7abde9a01fc482b4a2c
