apiVersion: v1
kind: Service
metadata:
  name: web-portfolio
  namespace: web-portfolio
  labels:
    environment: prod
spec:
  type: LoadBalancer
  selector:
    app: web-portfolio
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP